[world]
name = "siege_dojo"
seed = "siege_dojo_v8"

[namespace]
default = "siege_dojo"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "$DOJO_ACCOUNT_ADDRESS"
private_key = "$DOJO_PRIVATE_KEY"
world_address = "0x04134697f1327052025f01786d97effdf5de98528802aaaf3dc3c8896b57bc61"
