[world]
name = "siege_dojo"
seed = "siege_dojo_v7"

[namespace]
default = "siege_dojo"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "$DOJO_ACCOUNT_ADDRESS"
private_key = "$DOJO_PRIVATE_KEY"
world_address = "0x05ae03c23b817afa096a51e3b04e31c176f168ee8193465229d08fa67366a942"
